import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProviderWrapper } from "@/lib/providers/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import React from "react";
import AppStateProvider from "@/lib/providers/app-state-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProviderWrapper>
        <AppStateProvider>
          <Toaster />
          <body className={inter.className}>{children}</body>
        </AppStateProvider>
      </ThemeProviderWrapper>
    </html>
  );
}
